### ISSUE TITLE
Supporting earlier versions of Dart SDK

### ISSUE THREAD

**Issue by cyucelen** [ueman/unleash#12]
In order to make this repository more accessible for older projects, can we also maintain `0.1.x` versions (which depends `Dart SDK >=2.8`) for some time in a separate branch and release new features for `0.1.x` also?

**Comment by ueman** [comment]
I don't really have the time to maintain another branch, but if you're willing to do so. Then I'll take you up on the offer 👍

**Comment by cyucelen** [comment]
Sure, let's do it

**Comment by ueman** [comment]
Which commit do you want as a starting point?

**Comment by cyucelen** [comment]
I added the changes on top of `288c726bd712186996cb24daf7d600c5db8eadff`

**Comment by ueman** [comment]
You can now target your PR at https://github.com/ueman/unleash/tree/v0.1

**Comment by ueman** [comment]
I'll release a new v0.1.x version today 👍
